# Site settings
title: Arun Raj, Immersive Experiences Developer
description: Arun Raj, HoloLens Development, Immersive Experiences, Unity
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arun Raj
user_description: 
user_title: Developer, Immersive Experiences 
email: mail@arunraj.pw
twitter_username: _raj9
github_username:  0k1
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
